config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :gardens do
    resources :plants, only: [:new, :create]
  end

  resources :plants, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/garden.rb
class Garden < ApplicationRecord
  has_many :plants #come back to this
end

app/models/plant.rb
class Plant < ApplicationRecord
  belongs_to :garden
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/gardens_controller.rb
class GardensController < ApplicationController
  def show
    # raise
    @garden = Garden.find(params[:id])
  end
end

app/controllers/plants_controller.rb
class PlantsController < ApplicationController
  def new
    # raise
    @garden = Garden.find(params[:garden_id])
    @plant = Plant.new
  end

  def create
    @garden = Garden.find(params[:garden_id]) # garden is the garden_id coming from the url with the nested resource
    @plant = Plant.new(plants_strong_params)
    @plant.garden = @garden
    @plant.save!
    # raise
    redirect_to garden_path(@garden)
     # redirect_to garden_path(@plant.garden)
  end

  def destroy
    @plant = Plant.find(params[:id])
    @plant.destroy
    redirect_to garden_path(@plant.garden)
  end

  private

  def plants_strong_params
    params.require(:plant).permit(:name, :price, :image)
  end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gardens_helper.rb
module GardensHelper
end

app/helpers/plants_helper.rb
module PlantsHelper
end

app/views/gardens/show.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url('<%= @garden.banner %>');">
  <div class="container">
    <h1><%= @garden.name %></h1>
    <%= link_to 'add a plant', new_garden_plant_path(@garden), class: 'btn btn-primary'  %>
  </div>
</div>

<div class="container mt-5">
  <div class="row">
    <% @garden.plants.each do |plant| %>
    <div class="col-4">
      <%= image_tag plant.image, width: 200, height: 300 %>
      <div class="d-flex p-3">
          <p><%= plant.name.capitalize %></p>
          <br>
          <p><%= plant.price %>euros</p>

        <%= link_to 'destroy', plant_path(plant), method: :delete, data: {confirm: 'are you sure ?'}, class: 'btn btn-warning' %>
      </div>
    </div>
    <% end %>

  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ParksAndPlants</title>
      <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
      <%#= stylesheet_pack_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%#= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>

  <%= javascript_include_tag "application" %> <!-- from app/assets/javascripts/application.js -->
  <%#= javascript_pack_tag "application" %>
  </body>
</html>

app/views/plants/new.html.erb
    <h1>Add a new plant</h1>
<div class="container">
  <div class="row justify-content-center">
    <div class="col-6">

    <%= simple_form_for [@garden, @plant] do |f| %>
      <%= f.input :name %>
      <%= f.input :price %>
      <%= f.input :image %>
      <%= f.submit class: 'btn btn-primary'%>
    <% end %>
    </div>
  </div>
</div>